// <auto-generated />
using System;
using FinancialManagementApplication.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialManagementApplication.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260530085901_Migration260630_7")]
    partial class Migration260630_7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceManagementApplication.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.AllocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.ToTable("AllocationHistories");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.AssetHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.AssetHistoryDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetHistoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetHistoryId");

                    b.ToTable("AssetHistoryDetails");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InitialValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountID");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.PortfolioAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("FinancialCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioAllocations");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.AllocationHistory", b =>
                {
                    b.HasOne("FinancialManagementApplication.Domain.Entities.PortfolioAllocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allocation");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.AssetHistoryDetail", b =>
                {
                    b.HasOne("FinancialManagementApplication.Domain.Entities.AssetHistory", "AssetHistory")
                        .WithMany("Details")
                        .HasForeignKey("AssetHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetHistory");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.Assets", b =>
                {
                    b.HasOne("FinanceManagementApplication.Domain.Entities.Account", "Account")
                        .WithMany("Assets")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("FinanceManagementApplication.Domain.Entities.Account", "Account")
                        .WithMany("Portfolios")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.PortfolioAllocation", b =>
                {
                    b.HasOne("FinancialManagementApplication.Domain.Entities.Assets", "Asset")
                        .WithOne("PortfolioAllocation")
                        .HasForeignKey("FinancialManagementApplication.Domain.Entities.PortfolioAllocation", "AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinancialManagementApplication.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioAllocations")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FinanceManagementApplication.Domain.Entities.Account", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.AssetHistory", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.Assets", b =>
                {
                    b.Navigation("PortfolioAllocation")
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialManagementApplication.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("PortfolioAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
